// Comprehensive lists of skills, interests, and tools for Collab Unity

// All Interests (100 total)
export const ALL_INTERESTS = [
  // Creative & Design Interests (25)
  "Graphic Design",
  "Photography",
  "Videography",
  "UI/UX Design",
  "Creative Writing",
  "Web Design/Blogging",
  "Digital Art",
  "3D Modeling",
  "Music Production",
  "Game Design",
  "Calligraphy/Hand Lettering",
  "Animation",
  "Podcasting",
  "Filmmaking",
  "Fashion Design",
  "T-shirt/Merch Design",
  "Video Game Streaming",
  "Architectural Drafting",
  "Sculpting/Modeling",
  "Collage Art",
  "Furniture Restoration",
  "Product Photography",
  "Virtual Reality Creation",
  "Journalism/Reporting",
  "Lego/Model Building",
  
  // Technical & Analytical Interests (25)
  "Coding",
  "Data Science/Analytics",
  "Learning New Software",
  "Robotics/AI",
  "Cybersecurity",
  "Personal Finance",
  "Cryptocurrency/Blockchain",
  "Hardware Building",
  "Home Automation",
  "Statistical Modeling",
  "GIS Mapping",
  "Technical Writing",
  "Electronics Repair",
  "Spreadsheet Automation",
  "Machine Learning",
  "Foreign Language Study",
  "Search Engine Optimization (SEO)",
  "App Development",
  "Competitive Programming",
  "Biotechnology",
  "Astrophotography",
  "Tinkering/Inventing",
  "Online Course Completion",
  "Digital Archiving",
  "Spreadsheet Auditing",
  
  // Leadership & Community Interests (25)
  "Event Planning",
  "Volunteering Leadership",
  "Toastmasters/Public Speaking",
  "Mentoring/Tutoring",
  "Community Organizing",
  "Book Club Management",
  "Starting a Club",
  "Team Sports",
  "Fundraising",
  "Travel Planning",
  "Debate/Model UN",
  "Neighborhood Watch Leader",
  "Ethical Hacking",
  "Disaster Relief Participation",
  "Online Forum Moderation",
  "Peer Counseling/Support",
  "Local Government Participation",
  "Alumni Network Management",
  "Sales Pitch Practice",
  "Non-Profit Board Service",
  "Leading Workshops",
  "Conflict Mediation",
  "Career Coaching",
  "Public Policy Research",
  "Grant Writing Practice",
  
  // Practical & Physical Interests (25)
  "Advanced Cooking/Baking",
  "Homebrewing",
  "Woodworking/Carpentry",
  "Trail Running/Marathons",
  "Gardening/Horticulture",
  "Car Repair/Restoration",
  "Sewing/Tailoring",
  "Survival Skills/Prepping",
  "Welding/Metalwork",
  "Home Remodeling",
  "Fitness Training",
  "Permaculture Design",
  "Competitive E-Sports",
  "Sailing/Navigation",
  "Locksmithing",
  "Apiary/Beekeeping",
  "Interior Design",
  "Mixology",
  "DIY Maintenance",
  "Home Renovation",
  "Drone Operation",
  "Kombucha/Fermentation",
  "Geocaching",
  "Flipping Items",
  "Scuba Diving"
];

// All Skills (100 total - 50 Soft + 50 Hard)
export const ALL_SKILLS = [
  // Soft Skills (50)
  "Strategic Planning",
  "Conflict Resolution",
  "Cross-functional Collaboration",
  "Active Listening",
  "Stakeholder Management",
  "Executive Communication",
  "Client Relations",
  "Negotiation",
  "Mentorship",
  "Change Management",
  "Emotional Intelligence",
  "Critical Thinking",
  "Adaptability",
  "Process Improvement",
  "Time Management",
  "Data Interpretation",
  "Coaching",
  "Public Speaking",
  "Report Writing",
  "Root Cause Analysis",
  "Diplomacy",
  "Team Leadership",
  "Delegation",
  "Facilitation",
  "Business Acumen",
  "Feedback Delivery",
  "Problem Framing",
  "Customer Empathy",
  "Ethical Judgment",
  "Intercultural Communication",
  "Risk Assessment",
  "Motivation",
  "Conceptual Thinking",
  "Goal Setting",
  "Attention to Detail",
  "Patience",
  "Proactiveness",
  "Resilience",
  "Recruitment/Interviewing",
  "Vision Setting",
  "Relationship Building",
  "Work Ethic",
  "Self-Awareness",
  "Stress Management",
  "Innovation",
  "Presentation Design",
  "Meeting Management",
  "Decision Making",
  "Sustained Focus",
  "Creative Problem Solving",
  
  // Hard Skills (50)
  "SQL (Structured Query Language)",
  "Python (Programming Language)",
  "JavaScript",
  "Microsoft Excel (Advanced)",
  "Data Visualization",
  "Project Management (PMP/Agile/Scrum)",
  "SEO (Search Engine Optimization)",
  "CRM Software",
  "Cloud Platforms (AWS/Azure/GCP)",
  "Financial Modeling",
  "Statistical Analysis",
  "UX/UI Design",
  "Adobe Creative Suite",
  "Technical Writing",
  "Content Management Systems",
  "HTML/CSS",
  "Cybersecurity/Penetration Testing",
  "Email Marketing",
  "Sales Forecasting",
  "Budget Management",
  "Foreign Language Fluency",
  "API Integration",
  "Machine Learning",
  "Version Control (Git/GitHub)",
  "Google Analytics/AdWords",
  "A/B Testing",
  "Contract Negotiation",
  "Social Media Strategy",
  "Database Administration",
  "Bilingual/Multilingual Communication",
  "Market Research",
  "Data Mining",
  "CAD Software",
  "Software Development Lifecycle (SDLC)",
  "System Troubleshooting",
  "Payroll Processing",
  "Mobile App Development",
  "Wireframing",
  "Video Editing",
  "Inventory Management",
  "Accounting Software",
  "Public Relations",
  "Grant Writing",
  "Basic IT Support",
  "Process Mapping",
  "Survey Design",
  "Quality Assurance (QA)",
  "ETL (Extract, Transform, Load)",
  "Technical Sales",
  "Blogging/CMS Management"
];

// Comprehensive Tools List with URLs
export const ALL_TOOLS = [
  { name: "Figma", url: "https://www.figma.com", category: "Design" },
  { name: "Slack", url: "https://slack.com", category: "Communication" },
  { name: "Trello", url: "https://trello.com", category: "Project Management" },
  { name: "Jira", url: "https://www.atlassian.com/software/jira", category: "Project Management" },
  { name: "Notion", url: "https://www.notion.so", category: "Productivity" },
  { name: "GitHub", url: "https://github.com", category: "Development" },
  { name: "VS Code", url: "https://code.visualstudio.com", category: "Development" },
  { name: "Google Docs", url: "https://docs.google.com", category: "Productivity" },
  { name: "Miro", url: "https://miro.com", category: "Collaboration" },
  { name: "Discord", url: "https://discord.com", category: "Communication" },
  { name: "Airtable", url: "https://airtable.com", category: "Database" },
  { name: "HubSpot", url: "https://www.hubspot.com", category: "CRM" },
  { name: "Microsoft Office", url: "https://www.office.com", category: "Productivity" },
  { name: "Adobe Premiere Pro", url: "https://www.adobe.com/products/premiere.html", category: "Video Editing" },
  { name: "Adobe Photoshop", url: "https://www.adobe.com/products/photoshop.html", category: "Design" },
  { name: "Adobe Illustrator", url: "https://www.adobe.com/products/illustrator.html", category: "Design" },
  { name: "Sketch", url: "https://www.sketch.com", category: "Design" },
  { name: "Canva", url: "https://www.canva.com", category: "Design" },
  { name: "Asana", url: "https://asana.com", category: "Project Management" },
  { name: "Monday.com", url: "https://monday.com", category: "Project Management" },
  { name: "ClickUp", url: "https://clickup.com", category: "Project Management" },
  { name: "Zoom", url: "https://zoom.us", category: "Communication" },
  { name: "Google Meet", url: "https://meet.google.com", category: "Communication" },
  { name: "Microsoft Teams", url: "https://www.microsoft.com/en-us/microsoft-teams", category: "Communication" },
  { name: "Salesforce", url: "https://www.salesforce.com", category: "CRM" },
  { name: "Mailchimp", url: "https://mailchimp.com", category: "Email Marketing" },
  { name: "Hootsuite", url: "https://hootsuite.com", category: "Social Media" },
  { name: "Buffer", url: "https://buffer.com", category: "Social Media" },
  { name: "Tableau", url: "https://www.tableau.com", category: "Data Visualization" },
  { name: "Power BI", url: "https://powerbi.microsoft.com", category: "Data Visualization" },
  { name: "Google Analytics", url: "https://analytics.google.com", category: "Analytics" },
  { name: "AWS", url: "https://aws.amazon.com", category: "Cloud" },
  { name: "Azure", url: "https://azure.microsoft.com", category: "Cloud" },
  { name: "Google Cloud", url: "https://cloud.google.com", category: "Cloud" },
  { name: "Docker", url: "https://www.docker.com", category: "Development" },
  { name: "Kubernetes", url: "https://kubernetes.io", category: "Development" },
  { name: "WordPress", url: "https://wordpress.org", category: "Web Development" },
  { name: "Webflow", url: "https://webflow.com", category: "Web Development" },
  { name: "Shopify", url: "https://www.shopify.com", category: "E-commerce" },
  { name: "WooCommerce", url: "https://woocommerce.com", category: "E-commerce" },
  { name: "QuickBooks", url: "https://quickbooks.intuit.com", category: "Accounting" },
  { name: "Xero", url: "https://www.xero.com", category: "Accounting" },
  { name: "Stripe", url: "https://stripe.com", category: "Payment" },
  { name: "PayPal", url: "https://www.paypal.com", category: "Payment" },
  { name: "Zapier", url: "https://zapier.com", category: "Automation" },
  { name: "IFTTT", url: "https://ifttt.com", category: "Automation" },
  { name: "Calendly", url: "https://calendly.com", category: "Scheduling" },
  { name: "Loom", url: "https://www.loom.com", category: "Video" },
  { name: "OBS Studio", url: "https://obsproject.com", category: "Streaming" },
  { name: "Final Cut Pro", url: "https://www.apple.com/final-cut-pro", category: "Video Editing" },
  { name: "DaVinci Resolve", url: "https://www.blackmagicdesign.com/products/davinciresolve", category: "Video Editing" },
  { name: "Blender", url: "https://www.blender.org", category: "3D Modeling" },
  { name: "Unity", url: "https://unity.com", category: "Game Development" },
  { name: "Unreal Engine", url: "https://www.unrealengine.com", category: "Game Development" },
  { name: "AutoCAD", url: "https://www.autodesk.com/products/autocad", category: "CAD" },
  { name: "SolidWorks", url: "https://www.solidworks.com", category: "CAD" },
  { name: "InVision", url: "https://www.invisionapp.com", category: "Design" },
  { name: "Axure", url: "https://www.axure.com", category: "Design" },
  { name: "Framer", url: "https://www.framer.com", category: "Design" },
  { name: "Basecamp", url: "https://basecamp.com", category: "Project Management" },
  { name: "Smartsheet", url: "https://www.smartsheet.com", category: "Project Management" },
  { name: "Confluence", url: "https://www.atlassian.com/software/confluence", category: "Documentation" },
  { name: "Linear", url: "https://linear.app", category: "Project Management" },
  { name: "Height", url: "https://height.app", category: "Project Management" },
  { name: "GitLab", url: "https://gitlab.com", category: "Development" },
  { name: "Bitbucket", url: "https://bitbucket.org", category: "Development" },
  { name: "Postman", url: "https://www.postman.com", category: "API Testing" },
  { name: "Insomnia", url: "https://insomnia.rest", category: "API Testing" },
  { name: "MongoDB", url: "https://www.mongodb.com", category: "Database" },
  { name: "PostgreSQL", url: "https://www.postgresql.org", category: "Database" },
  { name: "MySQL", url: "https://www.mysql.com", category: "Database" },
  { name: "Redis", url: "https://redis.io", category: "Database" },
  { name: "Supabase", url: "https://supabase.com", category: "Database" },
  { name: "Firebase", url: "https://firebase.google.com", category: "Backend" },
  { name: "Vercel", url: "https://vercel.com", category: "Hosting" },
  { name: "Netlify", url: "https://www.netlify.com", category: "Hosting" },
  { name: "Heroku", url: "https://www.heroku.com", category: "Hosting" },
  { name: "DigitalOcean", url: "https://www.digitalocean.com", category: "Hosting" },
  { name: "Cloudflare", url: "https://www.cloudflare.com", category: "CDN" },
  { name: "Sentry", url: "https://sentry.io", category: "Monitoring" },
  { name: "Datadog", url: "https://www.datadoghq.com", category: "Monitoring" },
  { name: "New Relic", url: "https://newrelic.com", category: "Monitoring" },
  { name: "Mixpanel", url: "https://mixpanel.com", category: "Analytics" },
  { name: "Amplitude", url: "https://amplitude.com", category: "Analytics" },
  { name: "Segment", url: "https://segment.com", category: "Analytics" },
  { name: "Hotjar", url: "https://www.hotjar.com", category: "Analytics" },
  { name: "Intercom", url: "https://www.intercom.com", category: "Customer Support" },
  { name: "Zendesk", url: "https://www.zendesk.com", category: "Customer Support" },
  { name: "Freshdesk", url: "https://freshdesk.com", category: "Customer Support" },
  { name: "Help Scout", url: "https://www.helpscout.com", category: "Customer Support" },
  { name: "Twilio", url: "https://www.twilio.com", category: "Communication API" },
  { name: "SendGrid", url: "https://sendgrid.com", category: "Email" },
  { name: "ConvertKit", url: "https://convertkit.com", category: "Email Marketing" },
  { name: "ActiveCampaign", url: "https://www.activecampaign.com", category: "Email Marketing" },
  { name: "Grammarly", url: "https://www.grammarly.com", category: "Writing" },
  { name: "Hemingway Editor", url: "https://hemingwayapp.com", category: "Writing" },
  { name: "Evernote", url: "https://evernote.com", category: "Note-taking" },
  { name: "OneNote", url: "https://www.onenote.com", category: "Note-taking" }
];

// Filtered/common selections for quick access (backwards compatible)
export const COMMON_SKILLS = [
  "Web Development",
  "Mobile App Development", 
  "UI/UX Design",
  "Graphic Design",
  "Data Science/Analytics",
  "Machine Learning",
  "Marketing",
  "Content Writing",
  "Project Management (PMP/Agile/Scrum)",
  "Business Analysis",
  "Photography",
  "Video Editing",
  "Social Media Strategy",
  "SEO (Search Engine Optimization)",
  "Python (Programming Language)",
  "JavaScript",
  "React",
  "Node.js"
];

export const COMMON_TOOLS = [
  "Figma",
  "Slack",
  "Trello",
  "Jira",
  "Notion",
  "GitHub",
  "VS Code",
  "Google Docs",
  "Miro",
  "Discord"
];

export const COMMON_INTERESTS = [
  "Technology",
  "Startups",
  "Graphic Design",
  "Photography",
  "Music Production",
  "Writing",
  "Gaming",
  "Science",
  "Finance",
  "Health & Wellness",
  "Education",
  "Travel",
  "Sports"
];